# ======================================================================== #
#                    Yarn Spinner for Godot (GDScript)                     #
# ======================================================================== #
#                                                                          #
# (C) Yarn Spinner Pty. Ltd.                                               #
#                                                                          #
# Yarn Spinner is a trademark of Secret Lab Pty. Ltd.,                     #
# used under license.                                                      #
#                                                                          #
# This code is subject to the terms of the license defined                 #
# in LICENSE.md.                                                           #
#                                                                          #
# For help, support, and more information, visit:                          #
#   https://yarnspinner.dev                                                #
#   https://docs.yarnspinner.dev                                           #
#                                                                          #
# ======================================================================== #

@tool
extends RefCounted

const TRANSLATION_PREFIX := "YARN_"
const NEEDS_UPDATE_PREFIX := "(NEEDS UPDATE) "
const GENERATED_HEADER := "# Generated by Yarn Spinner from "
const DEFAULT_VARIABLES_PARENT := "YarnInMemoryVariableStorage"
const TAGGERS := ["random", "descriptive"]

const _GDSCRIPT_KEYWORDS := [
	"and", "as", "assert", "await", "break", "breakpoint", "class", "class_name",
	"const", "continue", "elif", "else", "enum", "extends", "false", "for", "func",
	"if", "in", "is", "match", "namespace", "not", "null", "or", "pass", "preload",
	"return", "self", "signal", "static", "super", "trait", "true", "var", "void",
	"when", "while", "yield", "INF", "NAN", "PI", "TAU",
]


static func read_project_json(project_path: String) -> Dictionary:
	var file := FileAccess.open(project_path, FileAccess.READ)
	if file == null:
		return {}
	var json := JSON.new()
	var err := json.parse(file.get_as_text())
	file.close()
	if err != OK or not json.data is Dictionary:
		return {}
	return json.data


static func write_project_json(project_path: String, data: Dictionary) -> Error:
	var file := FileAccess.open(project_path, FileAccess.WRITE)
	if file == null:
		return FileAccess.get_open_error()
	file.store_string(JSON.stringify(_whole_numbers_as_ints(data), "    ", false) + "\n")
	file.close()
	return OK


static func _whole_numbers_as_ints(value: Variant) -> Variant:
	if value is float and is_finite(value) and value == floorf(value):
		return int(value)
	if value is Dictionary:
		var result := {}
		for key: Variant in value:
			result[key] = _whole_numbers_as_ints(value[key])
		return result
	if value is Array:
		return (value as Array).map(_whole_numbers_as_ints)
	return value


static func read_import_options(project_path: String) -> Dictionary:
	var config := ConfigFile.new()
	var options := {}
	if config.load(project_path + ".import") != OK or not config.has_section("params"):
		return options
	for key in config.get_section_keys("params"):
		options[key] = config.get_value("params", key)
	return options


static func write_import_options(project_path: String, options: Dictionary) -> Error:
	var config := ConfigFile.new()
	var err := config.load(project_path + ".import")
	if err != OK:
		return err
	for key: String in options:
		config.set_value("params", key, options[key])
	return config.save(project_path + ".import")


static func find_yarn_projects(dir_path: String = "res://") -> PackedStringArray:
	var results := PackedStringArray()
	var fs := EditorInterface.get_resource_filesystem()
	var root := fs.get_filesystem_path(dir_path) if fs != null else null
	if root != null:
		_collect_files_with_extension(root, "yarnproject", results)
	return results


static func _collect_files_with_extension(dir: EditorFileSystemDirectory, extension: String, results: PackedStringArray) -> void:
	for i in dir.get_file_count():
		if dir.get_file(i).get_extension() == extension:
			results.append(dir.get_file_path(i))
	for i in dir.get_subdir_count():
		_collect_files_with_extension(dir.get_subdir(i), extension, results)


static func load_project_resource(project_path: String) -> Resource:
	if not ResourceLoader.exists(project_path):
		return null
	return ResourceLoader.load(project_path)


static func has_implicit_line_ids(project: Resource) -> bool:
	var info: Variant = project.get("line_info")
	if not info is Dictionary:
		return false
	for line_id: String in info:
		var entry: Variant = info[line_id]
		if entry is Dictionary and (entry as Dictionary).get("implicit", false):
			return true
	return false


static func add_line_tags(project_path: String, tagger: String) -> Dictionary:
	var project := load_project_resource(project_path)
	var summary := {"modified": PackedStringArray(), "errors": []}
	if project == null:
		summary.errors.append("Can't add line tags to %s, because it failed to import." % project_path)
		return summary

	var excluded := PackedStringArray()
	for other_path in find_yarn_projects():
		if other_path == project_path:
			continue
		var other := load_project_resource(other_path)
		if other == null:
			continue
		var info: Variant = other.get("line_info")
		if not info is Dictionary:
			continue
		for line_id: String in info:
			var entry: Variant = info[line_id]
			if entry is Dictionary and not (entry as Dictionary).get("implicit", false):
				excluded.append(line_id)

	var files: Array[Dictionary] = []
	var sources: Variant = project.get("source_files")
	if sources is PackedStringArray:
		for path: String in sources:
			var file := FileAccess.open(path, FileAccess.READ)
			if file == null:
				continue
			files.append({"fileName": path, "source": file.get_as_text()})
			file.close()

	if files.is_empty():
		summary.errors.append("%s has no Yarn scripts to tag." % project_path)
		return summary

	var result := YarnNativeCompiler.tag_lines(files, excluded, tagger)
	for error: Dictionary in result.errors:
		var file_name := ProjectSettings.localize_path(str(error.get("fileName", "")))
		var line: int = int(error.get("line", -1))
		if not file_name.is_empty() and line >= 0:
			summary.errors.append("Unable to tag line %d in %s: %s" % [line + 1, file_name, error.get("message", "")])
		else:
			summary.errors.append(str(error.get("message", "")))

	for tagged: Dictionary in result.files:
		if not tagged.get("modified", false):
			continue
		var path: String = tagged.get("fileName", "")
		var file := FileAccess.open(path, FileAccess.WRITE)
		if file == null:
			summary.errors.append("Can't write %s: %s" % [path, error_string(FileAccess.get_open_error())])
			continue
		file.store_string(tagged.get("source", ""))
		file.close()
		summary.modified.append(ProjectSettings.localize_path(path))

	return summary


static func write_strings_csv(project: Resource, destination: String, base_language: String) -> Error:
	var string_table: Variant = project.get("string_table")
	if not string_table is Dictionary:
		return ERR_INVALID_DATA

	var file := FileAccess.open(destination, FileAccess.WRITE)
	if file == null:
		return FileAccess.get_open_error()
	file.store_csv_line(PackedStringArray(["keys", base_language]))
	for line_id: String in _ordered_line_ids(project):
		file.store_csv_line(PackedStringArray([TRANSLATION_PREFIX + line_id, str(string_table[line_id])]))
	file.close()
	return OK


static func write_metadata_csv(project: Resource, destination: String) -> Error:
	var metadata: Variant = project.get("line_metadata")
	var info: Variant = project.get("line_info")
	if not metadata is Dictionary:
		return ERR_INVALID_DATA

	var file := FileAccess.open(destination, FileAccess.WRITE)
	if file == null:
		return FileAccess.get_open_error()
	file.store_csv_line(PackedStringArray(["id", "file", "node", "lineNumber", "metadata"]))
	for line_id: String in _ordered_line_ids(project):
		if not (metadata as Dictionary).has(line_id):
			continue
		var entry: Dictionary = (info as Dictionary).get(line_id, {}) if info is Dictionary else {}
		var tags := PackedStringArray()
		for tag in PackedStringArray(metadata[line_id]):
			if not tag.begins_with("line:"):
				tags.append(tag)
		if tags.is_empty():
			continue
		file.store_csv_line(PackedStringArray([
			line_id,
			str(entry.get("file", "")),
			str(entry.get("node", "")),
			str(entry.get("line", "")),
			" ".join(tags),
		]))
	file.close()

	var import_file := FileAccess.open(destination + ".import", FileAccess.WRITE)
	if import_file != null:
		import_file.store_string("[remap]\n\nimporter=\"keep\"\n")
		import_file.close()
	return OK


static func _ordered_line_ids(project: Resource) -> PackedStringArray:
	var string_table: Variant = project.get("string_table")
	var info: Variant = project.get("line_info")
	var ids: Array = (string_table as Dictionary).keys() if string_table is Dictionary else []
	if info is Dictionary and not (info as Dictionary).is_empty():
		var info_dict: Dictionary = info
		ids.sort_custom(func(a: String, b: String) -> bool:
			var ea: Dictionary = info_dict.get(a, {})
			var eb: Dictionary = info_dict.get(b, {})
			var fa := str(ea.get("file", ""))
			var fb := str(eb.get("file", ""))
			if fa != fb:
				return fa < fb
			return int(ea.get("line", 0)) < int(eb.get("line", 0))
		)
	return PackedStringArray(ids)


static func find_translation_csvs(project: Resource) -> PackedStringArray:
	var results := PackedStringArray()
	var string_table: Variant = project.get("string_table")
	if not string_table is Dictionary or (string_table as Dictionary).is_empty():
		return results

	var candidates := PackedStringArray()
	var fs := EditorInterface.get_resource_filesystem()
	if fs != null:
		_collect_files_with_extension(fs.get_filesystem(), "csv", candidates)

	for csv_path in candidates:
		var config := ConfigFile.new()
		if config.load(csv_path + ".import") != OK:
			continue
		if config.get_value("remap", "importer", "") != "csv_translation":
			continue
		if _csv_contains_any_key(csv_path, string_table):
			results.append(csv_path)
	return results


static func _csv_contains_any_key(csv_path: String, string_table: Dictionary) -> bool:
	var file := FileAccess.open(csv_path, FileAccess.READ)
	if file == null:
		return false
	file.get_csv_line()
	while not file.eof_reached():
		var row := file.get_csv_line()
		if row.is_empty():
			continue
		var key := row[0]
		if key.begins_with(TRANSLATION_PREFIX) and string_table.has(key.substr(TRANSLATION_PREFIX.length())):
			file.close()
			return true
	file.close()
	return false


static func csv_locales(csv_path: String) -> PackedStringArray:
	var locales := PackedStringArray()
	var file := FileAccess.open(csv_path, FileAccess.READ)
	if file == null:
		return locales
	var header := file.get_csv_line()
	file.close()
	for i in range(1, header.size()):
		if not header[i].is_empty() and not header[i].begins_with("_"):
			locales.append(header[i])
	return locales


static func update_translation_csvs(project_path: String, base_language: String) -> Dictionary:
	var summary := {"modified": PackedStringArray(), "errors": []}
	var project := load_project_resource(project_path)
	if project == null:
		summary.errors.append("Can't update strings files for %s, because it failed to import." % project_path)
		return summary

	var known_ids := {}
	for other_path in find_yarn_projects():
		var other := project if other_path == project_path else load_project_resource(other_path)
		if other == null:
			continue
		var table: Variant = other.get("string_table")
		if table is Dictionary:
			for line_id: String in table:
				known_ids[line_id] = true

	for csv_path in find_translation_csvs(project):
		var err := _update_translation_csv(csv_path, project, known_ids, base_language)
		if err == OK:
			summary.modified.append(csv_path)
		elif err != ERR_ALREADY_EXISTS:
			summary.errors.append("Can't update %s: %s" % [csv_path, error_string(err)])
	return summary


static func _update_translation_csv(csv_path: String, project: Resource, known_ids: Dictionary, base_language: String) -> Error:
	var string_table: Dictionary = project.get("string_table")
	var file := FileAccess.open(csv_path, FileAccess.READ)
	if file == null:
		return FileAccess.get_open_error()

	var header := file.get_csv_line()
	var rows: Array[PackedStringArray] = []
	while not file.eof_reached():
		var row := file.get_csv_line()
		if row.size() == 1 and row[0].is_empty():
			continue
		rows.append(row)
	file.close()

	var base_column := -1
	var locale_columns: Array[int] = []
	var standard_base := TranslationServer.standardize_locale(base_language)
	for i in range(1, header.size()):
		if header[i].is_empty() or header[i].begins_with("_"):
			continue
		if base_column == -1 and TranslationServer.standardize_locale(header[i]) == standard_base:
			base_column = i
		else:
			locale_columns.append(i)

	var modified := false
	var present := {}
	var kept: Array[PackedStringArray] = []
	for row in rows:
		var key := row[0]
		if not key.begins_with(TRANSLATION_PREFIX):
			kept.append(row)
			continue
		var line_id := key.substr(TRANSLATION_PREFIX.length())
		if not known_ids.has(line_id):
			modified = true
			continue
		present[line_id] = true
		if string_table.has(line_id) and base_column != -1:
			if row.size() < header.size():
				row.resize(header.size())
			var text := str(string_table[line_id])
			if row[base_column] != text:
				row[base_column] = text
				for column in locale_columns:
					if not row[column].is_empty() and not row[column].begins_with(NEEDS_UPDATE_PREFIX):
						row[column] = NEEDS_UPDATE_PREFIX + row[column]
				modified = true
		kept.append(row)

	for line_id in _ordered_line_ids(project):
		if present.has(line_id):
			continue
		var row := PackedStringArray()
		row.resize(header.size())
		row[0] = TRANSLATION_PREFIX + line_id
		if base_column != -1:
			row[base_column] = str(string_table[line_id])
		kept.append(row)
		modified = true

	if not modified:
		return ERR_ALREADY_EXISTS

	var out := FileAccess.open(csv_path, FileAccess.WRITE)
	if out == null:
		return FileAccess.get_open_error()
	out.store_csv_line(header)
	for row in kept:
		out.store_csv_line(row)
	out.close()
	return OK


static func variable_storage_classes() -> PackedStringArray:
	var bases := {}
	var paths := {}
	for entry: Dictionary in ProjectSettings.get_global_class_list():
		bases[entry["class"]] = entry["base"]
		paths[entry["class"]] = entry["path"]

	var results := PackedStringArray()
	for name: String in bases:
		if name == "YarnVariableStorage" or _is_generated_script(paths[name]):
			continue
		var current: String = bases[name]
		while bases.has(current):
			if current == "YarnVariableStorage":
				results.append(name)
				break
			current = bases[current]
	results.sort()
	return results


static func _is_generated_script(path: String) -> bool:
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		return false
	var first := file.get_line()
	file.close()
	return first.begins_with(GENERATED_HEADER)


static func variables_source_path(project_path: String, variables_class: String) -> String:
	return project_path.get_base_dir().path_join(variables_class.to_snake_case() + ".gd")


static func generate_variables_source(project_path: String, variables_class: String, parent_class: String, declarations: Array, enums: Array) -> String:
	var lines := PackedStringArray()
	lines.append(GENERATED_HEADER + project_path + ". Changes to this file will be overwritten.")
	lines.append("")
	lines.append("class_name %s" % variables_class)
	lines.append("extends %s" % parent_class)

	var reserved := _reserved_member_names(parent_class)
	var enum_info := {}

	for enum_type: Dictionary in enums:
		var enum_name: String = enum_type.get("name", "")
		var values_name := "_%s_VALUES" % enum_name.to_snake_case().to_upper()
		var is_string: bool = enum_type.get("rawType", "") == "String"
		var case_lines := PackedStringArray()
		var value_lines := PackedStringArray()
		var first_case := ""
		for enum_case: Dictionary in enum_type.get("cases", []):
			var case_name := _identifier(str(enum_case.get("name", ""))).to_snake_case().to_upper()
			if first_case.is_empty():
				first_case = case_name
			var raw: Variant = enum_case.get("value")
			var description := str(enum_case.get("description", ""))
			if not description.is_empty():
				case_lines.append("\t## %s" % description)
			if is_string:
				case_lines.append("\t%s = %d," % [case_name, _signed_crc32(str(raw))])
				value_lines.append("\t%s.%s: %s," % [enum_name, case_name, JSON.stringify(str(raw))])
			else:
				case_lines.append("\t%s = %d," % [case_name, int(raw)])
				value_lines.append("\t%s.%s: %s," % [enum_name, case_name, _float_literal(float(raw))])
		enum_info[enum_name] = {"values": values_name, "first": first_case}

		lines.append("")
		var enum_description := str(enum_type.get("description", ""))
		if not enum_description.is_empty():
			lines.append("## %s" % enum_description)
		lines.append("enum %s {" % enum_name)
		lines.append_array(case_lines)
		lines.append("}")
		lines.append("")
		lines.append("const %s := {" % values_name)
		lines.append_array(value_lines)
		lines.append("}")

	for decl: Dictionary in declarations:
		var yarn_name: String = decl.get("name", "")
		var yarn_type: String = decl.get("type", "")
		var property := _identifier(yarn_name.trim_prefix("$")).to_snake_case()
		if property in reserved or property in _GDSCRIPT_KEYWORDS:
			property += "_variable"
		reserved.append(property)

		var type_name := ""
		var getter := ""
		var setter := ""
		if decl.get("isEnum", false) and enum_info.has(yarn_type):
			var info: Dictionary = enum_info[yarn_type]
			type_name = yarn_type
			getter = "get_enum_value_or_default(%s, %s, %s.%s) as %s" % [JSON.stringify(yarn_name), yarn_type, yarn_type, info.first, yarn_type]
			setter = "set_value(%s, %s[value])" % [JSON.stringify(yarn_name), info.values]
		elif yarn_type == "Number":
			type_name = "float"
			getter = "float(get_value_or_default(%s, 0.0))" % JSON.stringify(yarn_name)
			setter = "set_value(%s, value)" % JSON.stringify(yarn_name)
		elif yarn_type == "String":
			type_name = "String"
			getter = "str(get_value_or_default(%s, \"\"))" % JSON.stringify(yarn_name)
			setter = "set_value(%s, value)" % JSON.stringify(yarn_name)
		elif yarn_type == "Bool":
			type_name = "bool"
			getter = "bool(get_value_or_default(%s, false))" % JSON.stringify(yarn_name)
			setter = "set_value(%s, value)" % JSON.stringify(yarn_name)
		else:
			push_warning("yarn project: can't generate a property for %s, because its type (%s) isn't supported" % [yarn_name, yarn_type])
			continue

		lines.append("")
		var description := str(decl.get("description", ""))
		if not description.is_empty():
			lines.append("## %s" % description)
		lines.append("var %s: %s:" % [property, type_name])
		lines.append("\tget:")
		lines.append("\t\treturn %s" % getter)
		if not decl.get("isInlineExpansion", false):
			lines.append("\tset(value):")
			lines.append("\t\t%s" % setter)

	return "\n".join(lines) + "\n"


static func write_variables_source(path: String, source: String) -> bool:
	if FileAccess.file_exists(path):
		var existing := FileAccess.open(path, FileAccess.READ)
		if existing != null:
			var current := existing.get_as_text()
			existing.close()
			if current == source:
				return false
			if not current.begins_with(GENERATED_HEADER):
				push_error("yarn project: not writing variables to %s, because a file that Yarn Spinner didn't generate is already there" % path)
				return false
	var file := FileAccess.open(path, FileAccess.WRITE)
	if file == null:
		push_error("yarn project: can't write %s: %s" % [path, error_string(FileAccess.get_open_error())])
		return false
	file.store_string(source)
	file.close()
	return true


static func _reserved_member_names(parent_class: String) -> PackedStringArray:
	var names := PackedStringArray()
	var script: Script = null
	for entry: Dictionary in ProjectSettings.get_global_class_list():
		if entry["class"] == parent_class:
			script = load(entry["path"]) as Script
			break
	var native_base := "Node"
	if script != null:
		for method: Dictionary in script.get_script_method_list():
			names.append(method.name)
		for property: Dictionary in script.get_script_property_list():
			names.append(property.name)
		for constant: String in script.get_script_constant_map():
			names.append(constant)
		native_base = script.get_instance_base_type()
	elif ClassDB.class_exists(parent_class):
		native_base = parent_class
	for method: Dictionary in ClassDB.class_get_method_list(native_base):
		names.append(method.name)
	for property: Dictionary in ClassDB.class_get_property_list(native_base):
		names.append(property.name)
	return names


static func _identifier(text: String) -> String:
	var result := ""
	for i in text.length():
		var c := text[i]
		if (c >= "a" and c <= "z") or (c >= "A" and c <= "Z") or (c >= "0" and c <= "9") or c == "_":
			result += c
		else:
			result += "_"
	if result.is_empty() or (result[0] >= "0" and result[0] <= "9"):
		result = "_" + result
	return result


static func _signed_crc32(text: String) -> int:
	var crc := 0xffffffff
	for byte in text.to_utf8_buffer():
		crc = crc ^ byte
		for i in 8:
			if crc & 1:
				crc = (crc >> 1) ^ 0xedb88320
			else:
				crc = crc >> 1
	var value := (~crc) & 0xffffffff
	if value > 2147483647:
		value -= 4294967296
	return value


static func _float_literal(value: float) -> String:
	var text := str(value)
	if not "." in text and not "e" in text and not "inf" in text and not "nan" in text:
		text += ".0"
	return text
